# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/knucklesfan/Documents/GitHub/KnuxfanWaiter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/knucklesfan/Documents/GitHub/KnuxfanWaiter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/knucklesfan/Documents/GitHub/KnuxfanWaiter/CMakeFiles /home/knucklesfan/Documents/GitHub/KnuxfanWaiter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/knucklesfan/Documents/GitHub/KnuxfanWaiter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

source/SDLTetris.o: source/SDLTetris.cpp.o
.PHONY : source/SDLTetris.o

# target to build an object file
source/SDLTetris.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/SDLTetris.cpp.o
.PHONY : source/SDLTetris.cpp.o

source/SDLTetris.i: source/SDLTetris.cpp.i
.PHONY : source/SDLTetris.i

# target to preprocess a source file
source/SDLTetris.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/SDLTetris.cpp.i
.PHONY : source/SDLTetris.cpp.i

source/SDLTetris.s: source/SDLTetris.cpp.s
.PHONY : source/SDLTetris.s

# target to generate assembly for a file
source/SDLTetris.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/SDLTetris.cpp.s
.PHONY : source/SDLTetris.cpp.s

source/background.o: source/background.cpp.o
.PHONY : source/background.o

# target to build an object file
source/background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/background.cpp.o
.PHONY : source/background.cpp.o

source/background.i: source/background.cpp.i
.PHONY : source/background.i

# target to preprocess a source file
source/background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/background.cpp.i
.PHONY : source/background.cpp.i

source/background.s: source/background.cpp.s
.PHONY : source/background.s

# target to generate assembly for a file
source/background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/background.cpp.s
.PHONY : source/background.cpp.s

source/globalgamemode.o: source/globalgamemode.cpp.o
.PHONY : source/globalgamemode.o

# target to build an object file
source/globalgamemode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/globalgamemode.cpp.o
.PHONY : source/globalgamemode.cpp.o

source/globalgamemode.i: source/globalgamemode.cpp.i
.PHONY : source/globalgamemode.i

# target to preprocess a source file
source/globalgamemode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/globalgamemode.cpp.i
.PHONY : source/globalgamemode.cpp.i

source/globalgamemode.s: source/globalgamemode.cpp.s
.PHONY : source/globalgamemode.s

# target to generate assembly for a file
source/globalgamemode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/globalgamemode.cpp.s
.PHONY : source/globalgamemode.cpp.s

source/opengl/buffermanager.o: source/opengl/buffermanager.cpp.o
.PHONY : source/opengl/buffermanager.o

# target to build an object file
source/opengl/buffermanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/buffermanager.cpp.o
.PHONY : source/opengl/buffermanager.cpp.o

source/opengl/buffermanager.i: source/opengl/buffermanager.cpp.i
.PHONY : source/opengl/buffermanager.i

# target to preprocess a source file
source/opengl/buffermanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/buffermanager.cpp.i
.PHONY : source/opengl/buffermanager.cpp.i

source/opengl/buffermanager.s: source/opengl/buffermanager.cpp.s
.PHONY : source/opengl/buffermanager.s

# target to generate assembly for a file
source/opengl/buffermanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/buffermanager.cpp.s
.PHONY : source/opengl/buffermanager.cpp.s

source/opengl/cube.o: source/opengl/cube.cpp.o
.PHONY : source/opengl/cube.o

# target to build an object file
source/opengl/cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/cube.cpp.o
.PHONY : source/opengl/cube.cpp.o

source/opengl/cube.i: source/opengl/cube.cpp.i
.PHONY : source/opengl/cube.i

# target to preprocess a source file
source/opengl/cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/cube.cpp.i
.PHONY : source/opengl/cube.cpp.i

source/opengl/cube.s: source/opengl/cube.cpp.s
.PHONY : source/opengl/cube.s

# target to generate assembly for a file
source/opengl/cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/cube.cpp.s
.PHONY : source/opengl/cube.cpp.s

source/opengl/line.o: source/opengl/line.cpp.o
.PHONY : source/opengl/line.o

# target to build an object file
source/opengl/line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/line.cpp.o
.PHONY : source/opengl/line.cpp.o

source/opengl/line.i: source/opengl/line.cpp.i
.PHONY : source/opengl/line.i

# target to preprocess a source file
source/opengl/line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/line.cpp.i
.PHONY : source/opengl/line.cpp.i

source/opengl/line.s: source/opengl/line.cpp.s
.PHONY : source/opengl/line.s

# target to generate assembly for a file
source/opengl/line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/line.cpp.s
.PHONY : source/opengl/line.cpp.s

source/opengl/model.o: source/opengl/model.cpp.o
.PHONY : source/opengl/model.o

# target to build an object file
source/opengl/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/model.cpp.o
.PHONY : source/opengl/model.cpp.o

source/opengl/model.i: source/opengl/model.cpp.i
.PHONY : source/opengl/model.i

# target to preprocess a source file
source/opengl/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/model.cpp.i
.PHONY : source/opengl/model.cpp.i

source/opengl/model.s: source/opengl/model.cpp.s
.PHONY : source/opengl/model.s

# target to generate assembly for a file
source/opengl/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/model.cpp.s
.PHONY : source/opengl/model.cpp.s

source/opengl/plane.o: source/opengl/plane.cpp.o
.PHONY : source/opengl/plane.o

# target to build an object file
source/opengl/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/plane.cpp.o
.PHONY : source/opengl/plane.cpp.o

source/opengl/plane.i: source/opengl/plane.cpp.i
.PHONY : source/opengl/plane.i

# target to preprocess a source file
source/opengl/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/plane.cpp.i
.PHONY : source/opengl/plane.cpp.i

source/opengl/plane.s: source/opengl/plane.cpp.s
.PHONY : source/opengl/plane.s

# target to generate assembly for a file
source/opengl/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/plane.cpp.s
.PHONY : source/opengl/plane.cpp.s

source/opengl/rect.o: source/opengl/rect.cpp.o
.PHONY : source/opengl/rect.o

# target to build an object file
source/opengl/rect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/rect.cpp.o
.PHONY : source/opengl/rect.cpp.o

source/opengl/rect.i: source/opengl/rect.cpp.i
.PHONY : source/opengl/rect.i

# target to preprocess a source file
source/opengl/rect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/rect.cpp.i
.PHONY : source/opengl/rect.cpp.i

source/opengl/rect.s: source/opengl/rect.cpp.s
.PHONY : source/opengl/rect.s

# target to generate assembly for a file
source/opengl/rect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/rect.cpp.s
.PHONY : source/opengl/rect.cpp.s

source/opengl/shader.o: source/opengl/shader.cpp.o
.PHONY : source/opengl/shader.o

# target to build an object file
source/opengl/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/shader.cpp.o
.PHONY : source/opengl/shader.cpp.o

source/opengl/shader.i: source/opengl/shader.cpp.i
.PHONY : source/opengl/shader.i

# target to preprocess a source file
source/opengl/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/shader.cpp.i
.PHONY : source/opengl/shader.cpp.i

source/opengl/shader.s: source/opengl/shader.cpp.s
.PHONY : source/opengl/shader.s

# target to generate assembly for a file
source/opengl/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/shader.cpp.s
.PHONY : source/opengl/shader.cpp.s

source/opengl/skybox.o: source/opengl/skybox.cpp.o
.PHONY : source/opengl/skybox.o

# target to build an object file
source/opengl/skybox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/skybox.cpp.o
.PHONY : source/opengl/skybox.cpp.o

source/opengl/skybox.i: source/opengl/skybox.cpp.i
.PHONY : source/opengl/skybox.i

# target to preprocess a source file
source/opengl/skybox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/skybox.cpp.i
.PHONY : source/opengl/skybox.cpp.i

source/opengl/skybox.s: source/opengl/skybox.cpp.s
.PHONY : source/opengl/skybox.s

# target to generate assembly for a file
source/opengl/skybox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/skybox.cpp.s
.PHONY : source/opengl/skybox.cpp.s

source/opengl/sota.o: source/opengl/sota.cpp.o
.PHONY : source/opengl/sota.o

# target to build an object file
source/opengl/sota.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sota.cpp.o
.PHONY : source/opengl/sota.cpp.o

source/opengl/sota.i: source/opengl/sota.cpp.i
.PHONY : source/opengl/sota.i

# target to preprocess a source file
source/opengl/sota.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sota.cpp.i
.PHONY : source/opengl/sota.cpp.i

source/opengl/sota.s: source/opengl/sota.cpp.s
.PHONY : source/opengl/sota.s

# target to generate assembly for a file
source/opengl/sota.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sota.cpp.s
.PHONY : source/opengl/sota.cpp.s

source/opengl/sprite.o: source/opengl/sprite.cpp.o
.PHONY : source/opengl/sprite.o

# target to build an object file
source/opengl/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sprite.cpp.o
.PHONY : source/opengl/sprite.cpp.o

source/opengl/sprite.i: source/opengl/sprite.cpp.i
.PHONY : source/opengl/sprite.i

# target to preprocess a source file
source/opengl/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sprite.cpp.i
.PHONY : source/opengl/sprite.cpp.i

source/opengl/sprite.s: source/opengl/sprite.cpp.s
.PHONY : source/opengl/sprite.s

# target to generate assembly for a file
source/opengl/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/sprite.cpp.s
.PHONY : source/opengl/sprite.cpp.s

source/opengl/stbi_image.o: source/opengl/stbi_image.c.o
.PHONY : source/opengl/stbi_image.o

# target to build an object file
source/opengl/stbi_image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/stbi_image.c.o
.PHONY : source/opengl/stbi_image.c.o

source/opengl/stbi_image.i: source/opengl/stbi_image.c.i
.PHONY : source/opengl/stbi_image.i

# target to preprocess a source file
source/opengl/stbi_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/stbi_image.c.i
.PHONY : source/opengl/stbi_image.c.i

source/opengl/stbi_image.s: source/opengl/stbi_image.c.s
.PHONY : source/opengl/stbi_image.s

# target to generate assembly for a file
source/opengl/stbi_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/stbi_image.c.s
.PHONY : source/opengl/stbi_image.c.s

source/opengl/texture.o: source/opengl/texture.cpp.o
.PHONY : source/opengl/texture.o

# target to build an object file
source/opengl/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/texture.cpp.o
.PHONY : source/opengl/texture.cpp.o

source/opengl/texture.i: source/opengl/texture.cpp.i
.PHONY : source/opengl/texture.i

# target to preprocess a source file
source/opengl/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/texture.cpp.i
.PHONY : source/opengl/texture.cpp.i

source/opengl/texture.s: source/opengl/texture.cpp.s
.PHONY : source/opengl/texture.s

# target to generate assembly for a file
source/opengl/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/texture.cpp.s
.PHONY : source/opengl/texture.cpp.s

source/opengl/triangle/tpp_assert.o: source/opengl/triangle/tpp_assert.cpp.o
.PHONY : source/opengl/triangle/tpp_assert.o

# target to build an object file
source/opengl/triangle/tpp_assert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_assert.cpp.o
.PHONY : source/opengl/triangle/tpp_assert.cpp.o

source/opengl/triangle/tpp_assert.i: source/opengl/triangle/tpp_assert.cpp.i
.PHONY : source/opengl/triangle/tpp_assert.i

# target to preprocess a source file
source/opengl/triangle/tpp_assert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_assert.cpp.i
.PHONY : source/opengl/triangle/tpp_assert.cpp.i

source/opengl/triangle/tpp_assert.s: source/opengl/triangle/tpp_assert.cpp.s
.PHONY : source/opengl/triangle/tpp_assert.s

# target to generate assembly for a file
source/opengl/triangle/tpp_assert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_assert.cpp.s
.PHONY : source/opengl/triangle/tpp_assert.cpp.s

source/opengl/triangle/tpp_impl.o: source/opengl/triangle/tpp_impl.cpp.o
.PHONY : source/opengl/triangle/tpp_impl.o

# target to build an object file
source/opengl/triangle/tpp_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_impl.cpp.o
.PHONY : source/opengl/triangle/tpp_impl.cpp.o

source/opengl/triangle/tpp_impl.i: source/opengl/triangle/tpp_impl.cpp.i
.PHONY : source/opengl/triangle/tpp_impl.i

# target to preprocess a source file
source/opengl/triangle/tpp_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_impl.cpp.i
.PHONY : source/opengl/triangle/tpp_impl.cpp.i

source/opengl/triangle/tpp_impl.s: source/opengl/triangle/tpp_impl.cpp.s
.PHONY : source/opengl/triangle/tpp_impl.s

# target to generate assembly for a file
source/opengl/triangle/tpp_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/opengl/triangle/tpp_impl.cpp.s
.PHONY : source/opengl/triangle/tpp_impl.cpp.s

source/pixfont.o: source/pixfont.cpp.o
.PHONY : source/pixfont.o

# target to build an object file
source/pixfont.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/pixfont.cpp.o
.PHONY : source/pixfont.cpp.o

source/pixfont.i: source/pixfont.cpp.i
.PHONY : source/pixfont.i

# target to preprocess a source file
source/pixfont.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/pixfont.cpp.i
.PHONY : source/pixfont.cpp.i

source/pixfont.s: source/pixfont.cpp.s
.PHONY : source/pixfont.s

# target to generate assembly for a file
source/pixfont.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/pixfont.cpp.s
.PHONY : source/pixfont.cpp.s

source/scenes/clock.o: source/scenes/clock.cpp.o
.PHONY : source/scenes/clock.o

# target to build an object file
source/scenes/clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/clock.cpp.o
.PHONY : source/scenes/clock.cpp.o

source/scenes/clock.i: source/scenes/clock.cpp.i
.PHONY : source/scenes/clock.i

# target to preprocess a source file
source/scenes/clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/clock.cpp.i
.PHONY : source/scenes/clock.cpp.i

source/scenes/clock.s: source/scenes/clock.cpp.s
.PHONY : source/scenes/clock.s

# target to generate assembly for a file
source/scenes/clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/clock.cpp.s
.PHONY : source/scenes/clock.cpp.s

source/scenes/debugscene.o: source/scenes/debugscene.cpp.o
.PHONY : source/scenes/debugscene.o

# target to build an object file
source/scenes/debugscene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/debugscene.cpp.o
.PHONY : source/scenes/debugscene.cpp.o

source/scenes/debugscene.i: source/scenes/debugscene.cpp.i
.PHONY : source/scenes/debugscene.i

# target to preprocess a source file
source/scenes/debugscene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/debugscene.cpp.i
.PHONY : source/scenes/debugscene.cpp.i

source/scenes/debugscene.s: source/scenes/debugscene.cpp.s
.PHONY : source/scenes/debugscene.s

# target to generate assembly for a file
source/scenes/debugscene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/debugscene.cpp.s
.PHONY : source/scenes/debugscene.cpp.s

source/scenes/knuxfanscreen.o: source/scenes/knuxfanscreen.cpp.o
.PHONY : source/scenes/knuxfanscreen.o

# target to build an object file
source/scenes/knuxfanscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/knuxfanscreen.cpp.o
.PHONY : source/scenes/knuxfanscreen.cpp.o

source/scenes/knuxfanscreen.i: source/scenes/knuxfanscreen.cpp.i
.PHONY : source/scenes/knuxfanscreen.i

# target to preprocess a source file
source/scenes/knuxfanscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/knuxfanscreen.cpp.i
.PHONY : source/scenes/knuxfanscreen.cpp.i

source/scenes/knuxfanscreen.s: source/scenes/knuxfanscreen.cpp.s
.PHONY : source/scenes/knuxfanscreen.s

# target to generate assembly for a file
source/scenes/knuxfanscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/knuxfanscreen.cpp.s
.PHONY : source/scenes/knuxfanscreen.cpp.s

source/scenes/mainmenu.o: source/scenes/mainmenu.cpp.o
.PHONY : source/scenes/mainmenu.o

# target to build an object file
source/scenes/mainmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/mainmenu.cpp.o
.PHONY : source/scenes/mainmenu.cpp.o

source/scenes/mainmenu.i: source/scenes/mainmenu.cpp.i
.PHONY : source/scenes/mainmenu.i

# target to preprocess a source file
source/scenes/mainmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/mainmenu.cpp.i
.PHONY : source/scenes/mainmenu.cpp.i

source/scenes/mainmenu.s: source/scenes/mainmenu.cpp.s
.PHONY : source/scenes/mainmenu.s

# target to generate assembly for a file
source/scenes/mainmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/mainmenu.cpp.s
.PHONY : source/scenes/mainmenu.cpp.s

source/scenes/solitaire.o: source/scenes/solitaire.cpp.o
.PHONY : source/scenes/solitaire.o

# target to build an object file
source/scenes/solitaire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/solitaire.cpp.o
.PHONY : source/scenes/solitaire.cpp.o

source/scenes/solitaire.i: source/scenes/solitaire.cpp.i
.PHONY : source/scenes/solitaire.i

# target to preprocess a source file
source/scenes/solitaire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/solitaire.cpp.i
.PHONY : source/scenes/solitaire.cpp.i

source/scenes/solitaire.s: source/scenes/solitaire.cpp.s
.PHONY : source/scenes/solitaire.s

# target to generate assembly for a file
source/scenes/solitaire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/solitaire.cpp.s
.PHONY : source/scenes/solitaire.cpp.s

source/scenes/weather.o: source/scenes/weather.cpp.o
.PHONY : source/scenes/weather.o

# target to build an object file
source/scenes/weather.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/weather.cpp.o
.PHONY : source/scenes/weather.cpp.o

source/scenes/weather.i: source/scenes/weather.cpp.i
.PHONY : source/scenes/weather.i

# target to preprocess a source file
source/scenes/weather.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/weather.cpp.i
.PHONY : source/scenes/weather.cpp.i

source/scenes/weather.s: source/scenes/weather.cpp.s
.PHONY : source/scenes/weather.s

# target to generate assembly for a file
source/scenes/weather.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/scenes/weather.cpp.s
.PHONY : source/scenes/weather.cpp.s

source/sine.o: source/sine.cpp.o
.PHONY : source/sine.o

# target to build an object file
source/sine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/sine.cpp.o
.PHONY : source/sine.cpp.o

source/sine.i: source/sine.cpp.i
.PHONY : source/sine.i

# target to preprocess a source file
source/sine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/sine.cpp.i
.PHONY : source/sine.cpp.i

source/sine.s: source/sine.cpp.s
.PHONY : source/sine.s

# target to generate assembly for a file
source/sine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/sine.cpp.s
.PHONY : source/sine.cpp.s

source/ttffont.o: source/ttffont.cpp.o
.PHONY : source/ttffont.o

# target to build an object file
source/ttffont.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/ttffont.cpp.o
.PHONY : source/ttffont.cpp.o

source/ttffont.i: source/ttffont.cpp.i
.PHONY : source/ttffont.i

# target to preprocess a source file
source/ttffont.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/ttffont.cpp.i
.PHONY : source/ttffont.cpp.i

source/ttffont.s: source/ttffont.cpp.s
.PHONY : source/ttffont.s

# target to generate assembly for a file
source/ttffont.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/ttffont.cpp.s
.PHONY : source/ttffont.cpp.s

source/utils/animation.o: source/utils/animation.cpp.o
.PHONY : source/utils/animation.o

# target to build an object file
source/utils/animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/animation.cpp.o
.PHONY : source/utils/animation.cpp.o

source/utils/animation.i: source/utils/animation.cpp.i
.PHONY : source/utils/animation.i

# target to preprocess a source file
source/utils/animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/animation.cpp.i
.PHONY : source/utils/animation.cpp.i

source/utils/animation.s: source/utils/animation.cpp.s
.PHONY : source/utils/animation.s

# target to generate assembly for a file
source/utils/animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/animation.cpp.s
.PHONY : source/utils/animation.cpp.s

source/utils/defs.o: source/utils/defs.cpp.o
.PHONY : source/utils/defs.o

# target to build an object file
source/utils/defs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/defs.cpp.o
.PHONY : source/utils/defs.cpp.o

source/utils/defs.i: source/utils/defs.cpp.i
.PHONY : source/utils/defs.i

# target to preprocess a source file
source/utils/defs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/defs.cpp.i
.PHONY : source/utils/defs.cpp.i

source/utils/defs.s: source/utils/defs.cpp.s
.PHONY : source/utils/defs.s

# target to generate assembly for a file
source/utils/defs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/utils/defs.cpp.s
.PHONY : source/utils/defs.cpp.s

source/wireframecube.o: source/wireframecube.cpp.o
.PHONY : source/wireframecube.o

# target to build an object file
source/wireframecube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/wireframecube.cpp.o
.PHONY : source/wireframecube.cpp.o

source/wireframecube.i: source/wireframecube.cpp.i
.PHONY : source/wireframecube.i

# target to preprocess a source file
source/wireframecube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/wireframecube.cpp.i
.PHONY : source/wireframecube.cpp.i

source/wireframecube.s: source/wireframecube.cpp.s
.PHONY : source/wireframecube.s

# target to generate assembly for a file
source/wireframecube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/source/wireframecube.cpp.s
.PHONY : source/wireframecube.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... source/SDLTetris.o"
	@echo "... source/SDLTetris.i"
	@echo "... source/SDLTetris.s"
	@echo "... source/background.o"
	@echo "... source/background.i"
	@echo "... source/background.s"
	@echo "... source/globalgamemode.o"
	@echo "... source/globalgamemode.i"
	@echo "... source/globalgamemode.s"
	@echo "... source/opengl/buffermanager.o"
	@echo "... source/opengl/buffermanager.i"
	@echo "... source/opengl/buffermanager.s"
	@echo "... source/opengl/cube.o"
	@echo "... source/opengl/cube.i"
	@echo "... source/opengl/cube.s"
	@echo "... source/opengl/line.o"
	@echo "... source/opengl/line.i"
	@echo "... source/opengl/line.s"
	@echo "... source/opengl/model.o"
	@echo "... source/opengl/model.i"
	@echo "... source/opengl/model.s"
	@echo "... source/opengl/plane.o"
	@echo "... source/opengl/plane.i"
	@echo "... source/opengl/plane.s"
	@echo "... source/opengl/rect.o"
	@echo "... source/opengl/rect.i"
	@echo "... source/opengl/rect.s"
	@echo "... source/opengl/shader.o"
	@echo "... source/opengl/shader.i"
	@echo "... source/opengl/shader.s"
	@echo "... source/opengl/skybox.o"
	@echo "... source/opengl/skybox.i"
	@echo "... source/opengl/skybox.s"
	@echo "... source/opengl/sota.o"
	@echo "... source/opengl/sota.i"
	@echo "... source/opengl/sota.s"
	@echo "... source/opengl/sprite.o"
	@echo "... source/opengl/sprite.i"
	@echo "... source/opengl/sprite.s"
	@echo "... source/opengl/stbi_image.o"
	@echo "... source/opengl/stbi_image.i"
	@echo "... source/opengl/stbi_image.s"
	@echo "... source/opengl/texture.o"
	@echo "... source/opengl/texture.i"
	@echo "... source/opengl/texture.s"
	@echo "... source/opengl/triangle/tpp_assert.o"
	@echo "... source/opengl/triangle/tpp_assert.i"
	@echo "... source/opengl/triangle/tpp_assert.s"
	@echo "... source/opengl/triangle/tpp_impl.o"
	@echo "... source/opengl/triangle/tpp_impl.i"
	@echo "... source/opengl/triangle/tpp_impl.s"
	@echo "... source/pixfont.o"
	@echo "... source/pixfont.i"
	@echo "... source/pixfont.s"
	@echo "... source/scenes/clock.o"
	@echo "... source/scenes/clock.i"
	@echo "... source/scenes/clock.s"
	@echo "... source/scenes/debugscene.o"
	@echo "... source/scenes/debugscene.i"
	@echo "... source/scenes/debugscene.s"
	@echo "... source/scenes/knuxfanscreen.o"
	@echo "... source/scenes/knuxfanscreen.i"
	@echo "... source/scenes/knuxfanscreen.s"
	@echo "... source/scenes/mainmenu.o"
	@echo "... source/scenes/mainmenu.i"
	@echo "... source/scenes/mainmenu.s"
	@echo "... source/scenes/solitaire.o"
	@echo "... source/scenes/solitaire.i"
	@echo "... source/scenes/solitaire.s"
	@echo "... source/scenes/weather.o"
	@echo "... source/scenes/weather.i"
	@echo "... source/scenes/weather.s"
	@echo "... source/sine.o"
	@echo "... source/sine.i"
	@echo "... source/sine.s"
	@echo "... source/ttffont.o"
	@echo "... source/ttffont.i"
	@echo "... source/ttffont.s"
	@echo "... source/utils/animation.o"
	@echo "... source/utils/animation.i"
	@echo "... source/utils/animation.s"
	@echo "... source/utils/defs.o"
	@echo "... source/utils/defs.i"
	@echo "... source/utils/defs.s"
	@echo "... source/wireframecube.o"
	@echo "... source/wireframecube.i"
	@echo "... source/wireframecube.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

